# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='rating',
        ),
        migrations.AddField(
            model_name='vote',
            name='story',
            field=models.ManyToManyField(to='story.Story'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
