# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20161022_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
