# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_story_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
