# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_vote_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_cast',
            field=models.IntegerField(default=0),
        ),
    ]
