# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_vote_vote_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=75),
        ),
    ]
